Experiment 0:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.1
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 72
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 1.0
  start: 0.0
Experiment 1:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.01
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 72
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 1.0
  start: 0.0
Experiment 10:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.1
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 304
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 2.0
  start: 0.0
Experiment 11:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.01
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 304
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 2.0
  start: 0.0
Experiment 12:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.1
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 72
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 5.0
  start: 0.0
Experiment 13:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.01
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 72
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 5.0
  start: 0.0
Experiment 14:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.1
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 154
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 5.0
  start: 0.0
Experiment 15:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.01
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 154
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 5.0
  start: 0.0
Experiment 16:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.1
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 304
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 5.0
  start: 0.0
Experiment 17:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.01
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 304
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 5.0
  start: 0.0
Experiment 2:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.1
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 154
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 1.0
  start: 0.0
Experiment 3:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.01
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 154
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 1.0
  start: 0.0
Experiment 4:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.1
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 304
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 1.0
  start: 0.0
Experiment 5:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.01
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 304
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 1.0
  start: 0.0
Experiment 6:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.1
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 72
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 2.0
  start: 0.0
Experiment 7:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.01
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 72
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 2.0
  start: 0.0
Experiment 8:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.1
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 154
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 2.0
  start: 0.0
Experiment 9:
  alpha: 50.0
  anisotropic: true
  batch_size: 1001
  dt: 0.01
  end: 20.0
  epochs: 100
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 20001
  partial_update: true
  particles: 154
  particles_batch_size: 20
  residual: 1
  restore: true
  restore_name: 500_res_steps/ckpt
  sigma: 2.0
  start: 0.0
