Experiment 0:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.1
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 15
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 1:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.01
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 15
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 10:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.01
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 25
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 11:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.001
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 25
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 12:
  adam_beta1: 0.95
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.1
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 25
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 13:
  adam_beta1: 0.95
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.01
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 25
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 14:
  adam_beta1: 0.95
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.001
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 25
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 15:
  adam_beta1: 0.99
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.1
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 25
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 16:
  adam_beta1: 0.99
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.01
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 25
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 17:
  adam_beta1: 0.99
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.001
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 25
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 2:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.001
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 15
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 3:
  adam_beta1: 0.95
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.1
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 15
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 4:
  adam_beta1: 0.95
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.01
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 15
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 5:
  adam_beta1: 0.95
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.001
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 15
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 6:
  adam_beta1: 0.99
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.1
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 15
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 7:
  adam_beta1: 0.99
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.01
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 15
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 8:
  adam_beta1: 0.99
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.001
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 15
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
Experiment 9:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adam_eta: 0.1
  batch_size: 50
  batching: true
  clean_batching: true
  clean_n_batches: 20
  end: 20.0
  kappa: 1.0
  lambda_: 0
  layer_size: 25
  layers: 1
  mass: 1.0
  method: Adam
  mu: 5
  n_batches: 200
  n_steps: 1001
  opt_steps: 1000
  res_steps: 1000
  start: 0.0
  tol: 1.0e-05
  transfer_learning: true
