fixed_arguments:
  start: 0.0
  end: 20.0
  n_steps: 10001
  kappa: 1.0
  mu: 8.53
  mass: 1.0
  layers: 1
  layer_size: 25
  residual: 1
  epochs: 200
  batch_size: 50
  particles_batch_size: 20
  alpha: 50.0
  l: 1.0
  anisotropic: true
  eps: 0.00001
  partial_update: true
  eval_freq: 10
  restore_name: '500_res_steps/ckpt'
variable_arguments:
  dt:
  - 0.01
  particles:
  - 76
  - 152
  - 304
  sigma:
  - 1.0
