Experiment 0:
  alpha: 50.0
  anisotropic: true
  batch_size: 50
  dt: 0.01
  end: 20.0
  epochs: 200
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 10001
  partial_update: true
  particles: 76
  particles_batch_size: 20
  residual: 1
  restore_name: 500_res_steps/ckpt
  sigma: 1.0
  start: 0.0
Experiment 1:
  alpha: 50.0
  anisotropic: true
  batch_size: 50
  dt: 0.01
  end: 20.0
  epochs: 200
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 10001
  partial_update: true
  particles: 152
  particles_batch_size: 20
  residual: 1
  restore_name: 500_res_steps/ckpt
  sigma: 1.0
  start: 0.0
Experiment 2:
  alpha: 50.0
  anisotropic: true
  batch_size: 50
  dt: 0.01
  end: 20.0
  epochs: 200
  eps: 1.0e-05
  eval_freq: 10
  kappa: 1.0
  l: 1.0
  layer_size: 25
  layers: 1
  mass: 1.0
  mu: 8.53
  n_steps: 10001
  partial_update: true
  particles: 304
  particles_batch_size: 20
  residual: 1
  restore_name: 500_res_steps/ckpt
  sigma: 1.0
  start: 0.0
