fixed_arguments:
  start: 0.0
  end: 20.0
  n_steps: 1001
  kappa: 1.0
  mu: 5
  mass: 1.0
  layers: 1
  layer_size: 15
  lambda_: 0
  batching: true
  n_batches: 200
  batch_size: 50
  clean_batching: true
  stimulate: true
  method: Adam
  adam_beta2: 0.999
  adam_eps: 0.00000001
  opt_steps: 2500
  transfer_learning: true
  res_steps: 2500
variable_arguments:
  adam_eta:
  - 0.001
  adam_beta1:
  - 0.99
  clean_n_batches:
  # - 10
  - 20
  layer_size:
  - 25
  - 50