name: ASM # Adjoint State Method
batching: true # needed for clean_batching
batch_size: 50
method: Adam # BFSG, CG, SLSQP, Adam
tol: 0.00001 # Only for BFGS, CG, SLSQP
lambda: 2.0 # Gradient regularisation
adam_eta: 0.1
adam_beta1: 0.9
adam_beta2: 0.999
adam_eps: 0.00000001
trajectory_training: true
epochs: 10
residual_training: false
epochs_res: 10
