name: CBO
alpha: 50.0
l: 1.0
eps: 0.00001
dt: 0.1
sigma: 1.0
lambda: 2.0 # regularisation of gradient
batching: True # Not meant to be False
batch_size: 50
particles: 200
particles_batch_size: 20
partial_update: true
anisotropic: true
cooling: false
trajectory_training: true
epochs: 3
residual_training: true
epochs_res: 3
